# Generated by Django 5.1.4 on 2025-01-06 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('dataCriacao', models.DateField()),
                ('sinopse', models.TextField()),
                ('anoLancamento', models.CharField(max_length=4)),
                ('avalicaoMedia', models.IntegerField(default=0)),
                ('imagemCapa', models.ImageField(upload_to='imagem_capa')),
                ('tipoObra', models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga'), ('manwar', 'Manwar')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='anime',
            fields=[
                ('obras_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animes.obras')),
                ('numero_episodes', models.CharField(max_length=100)),
            ],
            bases=('animes.obras',),
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('obras_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animes.obras')),
                ('numero_volumes', models.CharField(max_length=100)),
            ],
            bases=('animes.obras',),
        ),
        migrations.CreateModel(
            name='Manwar',
            fields=[
                ('obras_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animes.obras')),
                ('numero_pages', models.CharField(max_length=100)),
            ],
            bases=('animes.obras',),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUsuarios', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoPerfil', models.ImageField(upload_to='imagem_perfil')),
                ('favortios', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='animes.usuarios')),
            ],
        ),
    ]
