# Generated by Django 5.1.4 on 2025-01-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='anoLancamento',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='obras',
            name='dataCriacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
