# Generated by Django 5.1.4 on 2025-02-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_alter_obras_anolancamento_alter_obras_datacriacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='avaliacao',
            field=models.IntegerField(default=0),
        ),
    ]
